### ISSUE TITLE
exporting any types that rely on the SplitIO namespace results in compile errors in the consuming package

### ISSUE THREAD

**Issue by scamden** [splitio/javascript-client#138]
moduleA
```
import {SplitFactory} from '@splitsoftware/splitio';

export function mySplitFunc(attributes : SplitIO.Attributes){
 // do things
}
```
moduleB
```
import {mySplitFunc} from 'moduleA'

mySplitFunc({}); // throws "error TS2503: Cannot find namespace 'SplitIO'."
``

**Comment by SenhorCastor** [comment]
Hi Sterling,

We will take a look

**Comment by scamden** [comment]
@SenhorCastor thanks man :)

**Comment by NicoZelaya** [comment]
Hi Sterling!

Could you provide some more information about your `tsconfig` so I can try to reproduce your issue ? 

As well as if you can tell me how are you importing the SDK package. The declaration files are only available via npm at the moment, but if you're using the CDN package maybe you can copy the files from the repository and include them in your project, you can find them [here.](https://github.com/splitio/javascript-client/tree/master/types).

**Comment by scamden** [comment]
I'm definitely using npm, following the import method recommended in your docs:

```import { SplitFactory } from '@splitsoftware/splitio';```

i updated my original comment to reflect the import

then i have some code that internally creates a SplitClient based on passed params and exposes some methods for other packages to use. just like the example above.

the tsconfig.json for the split-web-client package is:

```{
  "compilerOptions": {
    "target": "es2015",
    "lib": [
      "esnext"
    ],
    "outDir": "dist",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "noImplicitAny": true,
    "removeComments": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noUnusedParameters": false,
    "noUnusedLocals": false,
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "@src/*": [
        "./src/*"
      ]
    },
    "plugins": [
      {
        "name": "tslint-language-service"
      }
    ]
  },
  "compileOnSave": false,
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

for the consuming package its
```
{
  "compilerOptions": {
    "target": "es6",
    "outDir": "dist",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "noImplicitAny": true,
    "removeComments": true,
    "sourceMap": true,
    "inlineSources": false,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noUnusedParameters": false,
    "noUnusedLocals": false,
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/@types/*", "*"],
      "@src/*": ["./src/*"],
      "@cmpts/*": ["./src/components/*"],
      "global.scss": ["./src/styles/global.scss"],
      "_variables.scss": ["./src/styles/_variables.scss"],
      "_mixins.scss": ["./src/styles/_mixins.scss"]
    },
    "plugins": [
      {
        "name": "tslint-language-service"
      }
    ]
  },
  "compileOnSave": false,
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useBabel": true,
    "useCache": true
  }
}

```

**Comment by SenhorCastor** [comment]
Thanks Sterling! This is helpful, we are going to replicate the scenario and come up with our findings.

Best
Fer

**Comment by NicoZelaya** [comment]
Ok, so let's try to cross some things out since I'm not being able to reproduce.

I see that the consuming package will use the `node` flavour for module resolution, so as the SDK package is a dependency of your `split-web-client` package, the module resolution should be able to get to it. 

- Could you please check that if you navigate through the `node_modules` folder to the split package, you see the `/types` folder with those files? 
- Are the example snippets accurate regarding the structure of your module? Do you see something like `export declare function mySplitFunc(attributes: SplitIO.Attributes): <some type>;` on the declaration files generated by the compilation of the `split-web-client` ?
- Are you using the `npm link` command to link the `split-web-client` package with the consuming one or that `split-web-client` is already published on npm?

**Comment by scamden** [comment]
the types are there yes, and no i'm not using link

here's the entire index.d.ts

```
export declare class SplitClient {
    splitInstance: SplitIO.IClient | undefined;
    treatmentCache: Map<string, string>;
    timedOut: boolean;
    splitKey: string;
    offlineMode: boolean;
    cacheTreatments: boolean;
    splitReady: Promise<boolean>;
    isOnOfflineMode: (featureName: string, attributes: SplitIO.Attributes) => boolean;
    constructor(key: string, apiKey: string, offlineMode: boolean, cacheTreatments: boolean, isOnOfflineMode: (featureName: string, attributes: SplitIO.Attributes) => boolean);
    isOn: (featureName: string, attributes?: SplitIO.Attributes) => boolean;
}
```

**Comment by scamden** [comment]
when you tried to repro, did you actually make two separate repos and publish the first to npm?

**Comment by NicoZelaya** [comment]
I've tried with symlinks for now.

Let's try to cross some other stuff. On your npm package for `split-web-client` are you specifying any directories or files to be ported with the module? Are your .ts files included on your `split-web-client` folder inside the `node_modules` folder of the consuming package?
I'm asking because:

- If the .ts/.tsx files are included, the compiler will be fine with you just having the import there. When it reads that file, it will know that it needs to import the Split declarations for you. If they are not already included, can you add them and try again?

- If your declaration file (the one you shared before) is just an ambient declaration (from the consuming package standpoint) as it has no reference to the Split declaration files and you have no direct import of the SDK package, the SplitIO namespace we provide may never be loaded into your context.
Try adding `/// <reference types="@splitsoftware/splitio" />` as the first line of your index.d.ts file on `split-web-client`. 
I know that manual step is not ideal, but I'll discuss with the team on how we can fit better for this use case.

Hope this helps!

**Comment by NicoZelaya** [comment]
Hey @scamden! 

Did you had the chance to test my suggestions? Are you still experiencing issues with the SplitIO namespace?

**Comment by scamden** [comment]
hey @NicoZelaya i'm sorry for the delay, i haven't had the chance to address the latest suggestions. for now i'm working around by not exporting any of the split types in my package. (i just duplicated the attributes type since it's fairly small)

to your questions i'm importing the package directly using a typings field, which should normally work perfectly with the compiled declaration files. i haven't tried the reference comment yet, but I had a feeling it might have something to do with your use of reference paths in the sdk. i don't have the bandwidth to revert the code and test with the sdk right now but i'll let you know if i get a chance to test again. i would recommend trying to repro without using npm link to see if you can get it happening.

**Comment by NicoZelaya** [comment]
Hey! Don't worry about the delay.

To clarify, I was able to reproduce using symlinks. I've tested both scenarios I've mentioned before writing the answer here.

As far as I know you are importing your client using a regular import, which does not necessarily import a dependence declaration file of a dependence (depends on more stuff). That actually imports the module `split-web-client` which does not include the Split declaration files in it. 
If that's not the case could you share some more information about the typings field import you're using? I'm not sure I'm following.

External type declarations should always be imported, unless you specify the dependency for those declarations from the DefinitelyTyped repository (we are not publishing there).

Please let me know when you have some time to check the points on [my previous comment](https://github.com/splitio/javascript-client/issues/138#issuecomment-375190542) or at least tell me if you're including your `.ts` files as part of `split-web-client` or not (to see if you're on case 1 or 2).
The explanations on that comment correspond with the TypeScript module resolution mechanism when using the node module resolution.

I'm confident that importing the SplitIO declaration as part of the ones for `split-web-client` will work without issues, but I'll be waiting for your comments!

Best,
Nico.

**Comment by scamden** [comment]
Hey nice, sorry again for the delay, i haven't had much bandwidth for this since i have a workaround. to answer the questions. We are compiling split-web-client with declaration: true so the ts compiler will look at the generated .d.ts files and not the original typescript (they are included unneccessarily however to answer your question.) normally things that are imported generate a reference line like you mentioned I try which i think is basically the bug here. i'm not sure what it is about the split types that is causing that ref not to be there, but normally importing a type form another package like this works perfectly fine as long as the dep is installed.  i think maybe the problem is that the SplitIO namespace is declared but not exported so there is no way for me to import it directly (i have to use it ambiently) which would create the ref i believe.
