### ISSUE TITLE
Ideal way to include in a webpack project?

### ISSUE THREAD

**Issue by rossPatton** [splitio/javascript-client#166]
So, i've been tasked recently with trying to cut our bundle size down at my work. Split is currently one of the largest packages in use, and not one we can cut. I've thought about trying to move all the logic server side, but before I wanted to try updating to v10, due to changes I saw that suggested a smaller bundle size.

After upgrading from `9.3.7` => `10.3.2` our bundle size actually went up by 1kb (after gzipping). No other changes.

afaik, `logplease` and `babel-runtime` are only used by split in my app, and i'd prefer they not be included in production, yet ignoring them via webpack will break Split. My understanding also is that Split includes it's own polyfills (correct me if i'm wrong), which we are already doing via `babel-env`

Is there a preferred way to include Split in a webpack project to mitigate bundle size? Maybe a pre-built file? 

<img width="680" alt="screen shot 2018-06-27 at 4 50 59 pm" src="https://user-images.githubusercontent.com/2379901/41999718-731bc7b4-7a2c-11e8-9b33-dec81450d4cf.png">

**Comment by NicoZelaya** [comment]
Hello Ross, hope you're having a good day. 

From version 9 to 10 we introduced breaking changes, we added support for ES6 modules, which was translated in a little bit more code. Sadly at the moment we do not offer a modular package for you to just load the storage pieces you want, etc. 
Making it more modular It's something we want to work on, but it's not into the roadmap yet.

Regarding polyfills, we do not pollute the global scope, but we use babel-runtime internally. We'll be most likely removing it on future release, but don't have a target date for you on that. 
Something similar applies for logplease library, which we are using for logging but we'll be removing in future relases. 
The SDK would break if you exclude them because they're using in runtime, same thing will happen if you remove axios for example.

What I would recommend would be to use the CDN package and use that, instead of the npm one, so you can try loading `<script src="//cdn.split.io/sdk/split-10.3.2.min.js"></script>` which will give you a global variable with the same factory you're importing from npm.
In that way you won't have Split as part of your bundle rather another asset downloading. It should improve loading times for your page a little bit while keeping your own bundle cleaner.

Does that make sense?

**Comment by rossPatton** [comment]
Sorry for the slow response. That all makes sense. I think the best thing for us to do then is to just wait for upcoming releases to trim the size down a bit. Thanks!

**Comment by NicoZelaya** [comment]
No worries at all! I'll close the issue for now. If there's something else we can do for you, feel free to open a new one here or send an email to support@split.io.

Best,
Nico.
