### ISSUE TITLE
Library size

### ISSUE THREAD

**Issue by probablyup** [splitio/javascript-client#210]
Hey there. My company is evaluating using split and I was tasked with investigating various things like bundle size impact, performance, etc.

One thing I noticed is this library is quite big for what it does: https://bundlephobia.com/result?p=@splitsoftware/splitio@10.5.0

Do you have any plans to trim this down? Ideally it should be no larger than 10kB gzipped for the browser (lib size is largely irrelevant on the server.)

If you don't have a punchlist already, some recommendations:

- Use smaller dependencies; all the lodash ones can probably be substituted with native functions or one of these tiny libraries (he's got something for everything): https://github.com/lukeed?tab=repositories. In general that bundlephobia site I linked earlier is _extremely_ helpful for discovering the real cost of dependencies. It's often a shock.

  <details>
    <summary>All installed dependencies</summary>
    <pre>
    ├─ @splitsoftware/splitio@10.5.0
    ├─ @types/node@10.9.4
    ├─ axios@0.18.0
    ├─ cluster-key-slot@1.0.12
    ├─ denque@1.4.0
    ├─ flexbuffer@0.0.6
    ├─ follow-redirects@1.5.10
    ├─ ioredis@3.2.2
    ├─ lodash.assign@4.2.0
    ├─ lodash.bind@4.2.1
    ├─ lodash.clone@4.5.0
    ├─ lodash.clonedeep@4.5.0
    ├─ lodash.defaults@4.2.0
    ├─ lodash.difference@4.5.0
    ├─ lodash.flatten@4.4.0
    ├─ lodash.foreach@4.5.0
    ├─ lodash.isempty@4.4.0
    ├─ lodash.keys@4.2.0
    ├─ lodash.noop@3.0.1
    ├─ lodash.partial@4.2.1
    ├─ lodash.pick@4.4.0
    ├─ lodash.sample@4.2.1
    ├─ lodash.shuffle@4.2.0
    ├─ lodash.values@4.3.0
    ├─ redis-commands@1.4.0
    ├─ redis-parser@2.6.0
    └─ utfx@1.0.1
     </pre>
  </details>

- Add a [`sideEffects` hint to package.json](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) so bundlers can do proper tree shaking on the library. Most JS is side-effect free if you write your code in a functional way, so I recommend starting with `false` and adding files as needed if they do contain side effectful code

- Make sure all your relevant code is wrapped in `process.env.NODE_ENV !== 'production'` if it's really not necessary for use in production. Newer bundlers like webpack 4 etc will automatically strip this stuff out at build time for production. This includes dev-time warnings, etc. In general, try to remove all the free-text you can from the library as it's hard to gzip. For inspiration on still providing useful error messages, feel free to steal the styled-components error implementation: https://github.com/styled-components/styled-components/blob/master/src/utils/error.js

- Eliminate strings where they're not necessary; often times people will do stuff like:

  ```js
  const things = {
    foo: 'foo',
    bar: 'bar',
  }
  ```

  Text is hard to compress, so using simple integers as the values is better and easier on the JS engine too:

  ```js
  const things = {
    foo: 1,
    bar: 2,
  }

  if (thatThing === things.foo) ...
  ```

**Comment by NicoZelaya** [comment]
Hey probablyup! 

Sorry the answer slipped through my fingers. First of all thank you so much for putting this together! It's very helpful. We do have some other ideas too that we'll work in future iterations.

While we will still have lots of code because of the complexity of the SDK (which is not shallow, it evaluates rules directly on the SDK so it requires an "engine" and few extra pieces to keep your private data on your side) there's more that we want to do to reduce the footprint of the SDK. Hopefully sooner rather than later!

Now to your points:

- The next dependencies we would like to try and remove or reduce the footprint are core-js and axios. All the lodash ones are just dev dependencies we use on the unit tests. You can see on your bundle (or at Bundlephobia directly) that those are not bundled with the SDK.
 We also have some intentions to reduce our own code footprint.

- I was not familiar with the sideEffects field, so thank you so much for pointing that out! I'll be sure to take a look at that when I have the chance. 
Either way, I don't think we have any side effects nowadays (we do not add global polyfills, nor monkey patch your methods. At most, we subscribe to things). I _think_ we should be safe.

- Our SDK does not understand the concept of environments, because it's meant to be used always in the same way. There's one thing that makes perfect sense to put behind it which is the localhost mode implementation (for testing/development). 
We already took the first steps a few months back by separating the module, but we've delayed it because we wanted to PoC on a modular SDK too (so you get only the storage you want, the factory you need, the API you use, etc). It'll definitely be part of the next iteration, either that or the trimming.

- On error logs, I'll be sure to share your recommendation with the team! Thing is that we also have a bunch of log messages that would probably be needed on your production build in case you need to diagnose unwanted behaviour. 
With those you can see why an evaluation returned a given treatment, what happened with your events queueing, etc (all optional logs of course, we also have log levels). But we can take a look at giving the same information in a less verbose manner if the size reduction proves worthy.

- On the enums thing, most of those (there are a few that are internals of JS) are standardized across SDKs. But I'll definitely keep it in mind while I'm working in it!

Again, thank you for taking the time to put all those great suggestions together! 
I'll close the issue for now but feel free to reopen if what I'm saying does not make sense to you or it's giving you too much pain. I'll work with you on resolving that while we keep improving our package size.

Best,
Nico.
