### ISSUE TITLE
Unhandled Promise rejection on Firefox

### ISSUE THREAD

**Issue by redbugz** [splitio/javascript-client#222]
I am getting this error on Firefox:
```
Unhandled promise rejection undefined split-10.5.1.min.js:formatted:5767
	t split-10.5.1.min.js:5767
	exports split-10.5.1.min.js:2521
	I split-10.5.1.min.js:5763
	exports split-10.5.1.min.js:5918
	<anonymous> split-10.5.1.min.js:2488
	g split-10.5.1.min.js:2478
	m split-10.5.1.min.js:2482
```

**Comment by NicoZelaya** [comment]
hey @redbugz ! Sorry for that missleading log. Thing is that when you get a timeout, we reject a promise we expose for you (which you can retrieve by calling the "ready" method of the client) and we had no catch for it.

As you probably know, any promise rejection that's not handled will result on it. So if you don't consume it and there's a timeout event, you'll get that log. The log should be harmless and do not affect the functionality at all.

It's already fixed on our development branch and we'll release a stable version early next week alongside other changes. 
In case you wanna get rid of the log, just retrieve the promise and add a catch clause where you get the client, e.g.:

`client.ready().catch(function() {})`

Again, sorry for the inconveniences! I could notify you here if you would like once it's 100% out.

Best,
Nico.

**Comment by redbugz** [comment]
Any ideas why it only happens on Firefox? Chrome and Safari don't seem to throw that error.

I don't see any documentation for the `ready()` function, but I do see it on the client.
Is this it? https://github.com/splitio/javascript-client/blob/master/types/splitio.d.ts#L279

Do I just call this after my on listener like this:
```
splitSessionClient.on(splitSessionClient.Event.SDK_READY, function () {
  //...
});
splitSessionClient.ready().catch(function() {})
```

**Comment by NicoZelaya** [comment]
My apologies @redbugz , I missed the piece of it only happening on FF, you may not solve it by using the catch. (I could share a release candidate either way where we'll add the catch clause for you if it's not there, I'll be releasing it soon.)

At the very least I can confirm it started happening around version 64. Could you tell me for which services/endpoints are you experiencing those? Could it be that it happens when the SDK tries to post to the endpoints below?

```
https://events.split.io/api/metrics/counters
https://events.split.io/api/metrics/times
https://events.split.io/api/testImpressions/bulk
```

If it's failing for those, we have confirmed that it won't affect the functionality. Our BE is missing a header on the response setting the right Content-Type/Content-Length and Firefox tries to parse a response body that's just empty. 
Seems like the other browsers do not care about that header and just don't try to parse that missing response body.

The team will be working on this in the short term so we get rid of that ugly log. Again, my apologies for both missing the Firefox piece as well as the error you're getting. 
If you can confirm we're on the right track or if you're seeing a different issue, we'll really appreciate it.

Have a wonderful start of your week!
Nico.

**Comment by redbugz** [comment]
I was also getting XML parsing errors from those endpoints in Firefox. Adding the catch seems to have caused all of the errors to go away

**Comment by NicoZelaya** [comment]
hey @redbugz ! Could you give it a try to the `10.6.0` version of the SDK? You can see the changes included here: https://github.com/splitio/javascript-client/blob/development/NEWS.txt

While it will not address the missing `Content-Length: 0` causing the parsing errors on FF (prioritized for the near future, will be fixed from our Server), it should address the other ones without the need of your empty catch clause.

Please let me know how it goes!

Best,
Nico.

**Comment by NicoZelaya** [comment]
Thank you for reporting in the first place! I'll go ahead and close the issue, but feel free to reopen or create a new one if you're still experiencing any problems.

Regards,
Nico.
