### ISSUE TITLE
splitio v10.6.1 error when using with node 0.10.x

### ISSUE THREAD

**Issue by cecilialam** [splitio/javascript-client#238]
the SDK v10.6.1 throws 'TypeError: object is not a function' at GateContext during startup of my legacy module using node v0.10.36.
`TypeError: object is not a function
        at GateContext (/Users/myuser/myrepo/node_modules/@splitsoftware/splitio/lib/readiness/index.js:38:16)
        at SplitFactory (/Users/myuser/myrepo/node_modules/@splitsoftware/splitio/lib/index.js:82:45)
...`

I have to use v9.3.2 with the older way to instantiate the split.io.

**Comment by chillaq** [comment]
Hi, I can repro this using same node version, however, using node v8.11.4 works fine with latest Split SDK. 
We will check internally this issue.

**Comment by NicoZelaya** [comment]
Hey @cecilialam !!

Sadly what you're seeing there is kind of expected, since we ensure support from Node 4 going forward (already reached EOL a year ago) which is the oldest version we run our automation with.

We do not test for Node versions as old as 0.10 (reached EOL in 2016).

The offender there (but you may find more issues if you solve this one) is the events module. Current Node versions retrieve the EventEmitter class when you import the package, so you have:
```javascript
const EventEmitter = require('events');

const myEmitter = new EventEmitter();
```
Source: https://nodejs.org/api/events.html#events_events

But on 0.10, the API was different and it had an "EventEmitter" prop:
```javascript
const EventsModule = require('events);
const EventEmitter = EventsModule.EventEmitter;

const myEmitter = new EventEmitter();
```
Source: https://nodejs.org/docs/latest-v0.10.x/api/events.html#events_events

So basically we're trying to create a new instance of EventEmitter on the SDK, but as we use the current API format, it's trying to call the module as a function. 
You could potentially fix this by installing the "events" npm package: https://www.npmjs.com/package/events

Either way if you need to keep updating that legacy server and you can't get around it (assuming that installing events from npm is still giving you pain), you should be able to transpile and add the necessary polyfills yourself using Babel and Webpack or a similar setup.

You'll need to process the code inside the `/src` folder of the npm package we distribute yourself as some sort of "before script" step. 

I know that transpiling an npm package is not ideal and may not be trivial depending on your setup, so if you need more help, please reach out through support@split.io with more details! 

Best regards,
Nico.
