### ISSUE TITLE
Track method overload choosing a wrong one

### ISSUE THREAD

**Issue by DzmVasileusky** [splitio/javascript-client#331]
I'm using Typescript in my project.
I have integrated split from npm @splitsoftware/splitio (v10.9.2).

```
        const splitio: SplitIO.ISDK = SplitFactory({
                core: {
                    authorizationKey: config.splitApiKey,
                    key: 'some_key'
                }
        });

        const splitClient: SplitIO.IClient = this.splitio.client();

        const isReadyEvent = fromEvent(splitClient, splitClient.Event.SDK_READY);
        isReadyEvent.pipe(take(1)).subscribe({
            next: () => {

                splitClient.track('Initialized', 1, { someProp: 'Some value' });

            }
        });
```

It perfectly overlaps with 
`track(eventType: string, value?: number, properties?: Properties): boolean`

but I got two errors
```
[ERROR] track: you passed an invalid event_type, event_type must be a non-empty string.
[ERROR] track: value must be a finite number.
```

Then I went through debugger and got
```
client.track = function track(
  maybeKey, // undefined
  maybeTT, // 'Initialized'
  maybeEvent, // 1
  maybeEventValue, //  { someProp: 'Some value' }
  maybeProperties // undefined
)
```

As you can see event name was mapped to traffic type and all the other properties were mapped wrong as well.

**Comment by ryandv1** [comment]
Hi Dzmitry, 

You are missing event_type which must be specified with the track call if you don't define it in the factory setting or when you create a client.

Your traffic type should match the traffic types you have defined within your org (such as 'user' or 'account'.) You also use double quotes for strings in properties.

Your call would look like this:

 splitClient.track('user', 'Initialized', 1, { someProp: "Some value" });

Additional examples can be found here: https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#track

**Comment by DzmVasileusky** [comment]
I tried 

`splitClient.track(undefined, 'Initialized', 1, { someProp: 'Some value' });`
but got
`[ERROR] track: you passed a null or undefined traffic_type_name, traffic_type_name must be a non-empty string.`

It seems like traffic_type_name is a required parameter so why 
`track(eventType: string, value?: number, properties?: Properties): boolean` is in splitio.d.ts?

**Comment by NicoZelaya** [comment]
The idea of allowing you to define it on instantiation is to avoid the need to pass it on every call, it's just a convenience feature. 
But the traffic type is still required for an event, you have to pass it along to the SDK in one of the two ways. Both options being:

- If you've set the traffic type as part of the factory configuration, you should use the signature you were previously using (without traffic type on each .track() call).
- Instead, if you've NOT set the traffic type on the configuration, you should use the signature with the traffic type as the first parameter, being the traffic type a valid one. 

Since both signatures exist we've overloaded that signature to have both options in the TS declaration files of the SDK. You can choose which one you want to use since both are valid depending on the config.
Hope that makes sense! I'll keep this in mind to check later if we can make our declaration files infer which one you need to use.

The traffic type should match the one you've defined in the Split web application. (I think the default is "user")

If you want to read more about the event parameters and what are the requirements and constraints for each one, you can take a look here: https://help.split.io/hc/en-us/articles/360020585772-Track-events

My apologies for the confusion! We'll try to make the documentation clearer.

Best,
Nico.

**Comment by DzmVasileusky** [comment]
@NicoZelaya Thank you
