### ISSUE TITLE
Unclear or difference in behaviour when passing in a user context

### ISSUE THREAD

**Issue by EwanValentine** [splitio/javascript-client#336]
We're using this in both a front-end project and a nodejs project. In the front-end project, we're passing in a 'tenant', which refers to a segment of users called 'tenant' in Split. Like so:

```javascript
factory.client(tenant, 'tenant');
```

However, when we try to replicate this pattern in a nodejs application, we get the following error:
```
Shared Client not supported by the storage mechanism. Create isolated instances instead.
```

I can't find an explanation as to why this might be for a nodejs instance in the documentation. 

Also, in the node version, the first arg to `getTreatment` is `key` which we're not sure about. The only mention I could find of what key is, is:
```
When the SDK_READY event fires, you can use the getTreatment method to return the proper treatment based on the SPLIT_NAME attribute you pass and the key attribute you passed when instantiating the SDK.
```

The only key we pass in when instantiating the sdk is the auth key. I've tried passing this in, and I've tried passing in the tenant as the third param `attributes`, but we get `control` back instead of `on` or `off`. Could I get some clarification around passing in a segment/user context, please?

Thanks in advance!

**Comment by EwanValentine** [comment]
We figured this out, we had to upgrade our version to `10.10.0 canary`. We needed to set the `key` in `getTreament` to our tenant.

**Comment by NicoZelaya** [comment]
Hi @EwanValentine ! 

I'm glad you could sort it out. Basically our SDK does not work in the exact same way in Node than in the browser. 
In Node it's usually preferable to have a long living client that can evaluate for all your different tenants, while in the browser you're usually evaluating for only one or two IDs. That's why in one you "bind" the tenant to that client while in Node it needs to be passed on each getTreatment call.

When looking at our docs focus on the page for which you're running code with, the JS and the Node ones have some different sections and snippets.

Also, I wouldn't suggest using a canary tagged version unless instructed to do so by Split engineers. Those are our release candidates that will go into testing and we can't guarantee these are stable. 

In any case, thanks for closing the issue after figuring it out. Hope you have a great start of the year!

Best,
Nico.
