### ISSUE TITLE
Missing package: 'dns' when used in browser

### ISSUE THREAD

**Issue by martaver** [splitio/javascript-client#355]
I'm using the `@splitsoftware/splitio@10.10.0` npm package in my project (no CDN).

The reason I'm using the npm package is because it's a typescript project, and I want to use the typings available in it.

I'm following the instructions available in the 'getting started' tutorial:
https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#2-instantiate-the-sdk-and-create-a-new-split-client

I'm bundling the project with fuse-box, and when I create a split.io client in the browser, I get the following error:
```
Uncaught Package not found dns
```

It looks like `dns` is a dependency of `ioredis` and it's a `nodejs` package... for this reason, fuse-box throws an error when trying to load it in a browser environment.

If I am understanding your tutorial correctly, the JavaScript SDK available on NPM should work in browser... is this just a matter of having the wrong version of the ´dns´ dependency used in a package? 

Not sure why the browser-side SDK is trying to call a nodejs package... unless I am misunderstanding something.

Could you give us a hand in getting this working, please?

**Comment by NicoZelaya** [comment]
Hi @Martaver ! I'm sorry to hear that you're having inconveniences to integrate our SDK.

The issue seems to be related with how is fuse-box resolving packages in the event of a package.json. There are some pieces of the code, like our storage implementation, where we have a version for the browser~like and a different one for Node~like environments.

The way we are instructing bundler tools/build systems to do that is by defining package.json files in the folders where we have both implementations, where we set which implementation is for each "side". 

Those package.json look like this:
```
{
  "main": "./node.js",
  "browser": "./browser.js"
}
```

For example, this is how Webpack handles those: https://webpack.js.org/configuration/resolve/#resolvemainfields

Are you aware of the setting to control this in fuse-box? We'll also do some research on our end.

**Comment by NicoZelaya** [comment]
@Martaver maybe give this one a try? 
https://fuse-box.org/docs/development/configuration#target

**Comment by Martaver** [comment]
Hi, this is great, thanks for the feedback. I came to the same conclusion.
My target is set to browser but fuse-box seems to be ignoring browser
property in package.json for child deps. I think this is a bug with fb in
the end and I’ll chase it down with them. @nchanged

**Comment by NicoZelaya** [comment]
Hi @Martaver ! 

I'll go ahead and close this issue soon but feel free to reopen afterwards if needed.
In the meantime, are you still blocked? Could you use the CDN until fuse-box issue is resolved? 

Thanks in advance,
Nico.
