### ISSUE TITLE
Track return boolean rather than a promise resolving to a boolean as docs suggest

### ISSUE THREAD

**Issue by JCB-K** [splitio/javascript-client#363]
The docs say that are slightly confusing. First it says this:

> The track method returns a boolean value of true or false to indicate whether or not the SDK was able to successfully queue the event to be sent back to Split's servers on the next event post. The SDK will return false if the current queue size is equal to the config set by eventsQueueSize or if an incorrect input to the track method has been provided.

But a few lines down in the example I see the following:

```js
// The track function returns a promise which will resolve to a boolean, indicating if the event was correctly queued or not.
queuedPromise.then(function(queued) {
  console.log(queued ? 'Successfully queued event' : 'Failed to queue event');
});
```

As far as I can tell it's the former that's correct, but personally I would quite like the behaviour of the second. How is the function supposed to behave?

Additional question, is it possible to track if the event was succesfully send to the server on the next post?

**Comment by chillaq** [comment]
Hi Jacob, the track method does return a promise when it is queued successfully, did you see any issue when treating it as a promise?

Thanks
Bilal

**Comment by JCB-K** [comment]
Yes, here is an example of an issue. Running split.io 10.10 on Node 12.13.

```js
const { SplitFactory } = require('@splitsoftware/splitio');

const factory = SplitFactory({
  core: {
    authorizationKey: '...',
  },
});
const splitIoClient = factory.client();

const result = splitIoClient.track(123, 'user', 'testEvent');
console.log(typeof result); // string
result.then(a => {
  console.log(result); 
}) // TypeError: splitIoClient.track(...).then is not a function
```

**Comment by JCB-K** [comment]
I'm guessing the issue might be located here? https://github.com/splitio/javascript-client/blob/development/src/client/client.js#L139-L144

**Comment by chillaq** [comment]
You are correct, the track method returns promise only if Redis storage option is used, we will update our doc to reflect this.

Thanks
Bilal

**Comment by JCB-K** [comment]
Wouldn't it make more sense to always return a promise, so that one can log the error in a proper way? I recently had an issue with tracking, and logs looked something like this:

- split.io SDK: property object too big
- my code: split.io couldn't track event Y

Neither gives enough context to properly debug: the former doesn't log the event data I need, and the latter doesn't know _why_ the track call failed. Returning a promise would allow to do something like this:

```js
const myEvent = 'some event';

sdk.track(123, 'user', 'some event').then(() => {
  log('successfully tracked event %s', myEvent)
}).catch((e) => {
  log('couldnt track event %s due to error %j', myEvent, e)
})
```

The 2nd log call would be something like this 

```
couldnt track event 'some event' due to error 'property object too big'
```

Which puts all the relevant context in one place, making debugging a lot easier.

I understand that this is a breaking change to the API that might not be easy to get in, but wanted to give my perspective as a user here :).

**Comment by NicoZelaya** [comment]
Hi @JCB-K ! 

I can see the value in that because you might not always want to use both our log and yours. Providing that feedback of the error would allow you to track it on an external tool? Or mostly interested in development time feedback?

In any case, we try not to force it to be a promise because then all of those need to be handled. If we don't do that we will have a lot of warnings in node that would eventually crash node processes.

`(node:66333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I'll log your feedback of both having a promise API and to provide a way to handle errors. Do you think that if we provide, for example, an error handler callback or SDK_ERROR event/s to listen to it would allow you to achieve your goals?
