### ISSUE TITLE
Updates in version 10.9.0 break Parcel compilation

### ISSUE THREAD

**Issue by drewbolles** [splitio/javascript-client#388]
Compiling split.io libraries (both vanilla JS and React) with Parcel throws an error:

`TypeError: Incompatible receiver, Map required`

I traced this issue to updates made in version in [10.9.0](https://github.com/splitio/javascript-client/blob/development/CHANGES.txt#L27), 10.8.4 compiles fine.

I've created a repo to demonstrate the bug: https://github.com/drewbolles/parcel-split-debug

After cloning run `npm i && npm serve` and visit the development URL in a browser. You should see the error in the console.

I was unable to figure out the literal cause of the error, but it seems to be related to how Split uses `core-js` and how Parcel uses it.

**Comment by chillaq** [comment]
Thanks for the details, we are checking the issue now.

**Comment by smeijer** [comment]
@chillaq, were you able to find something? I'm having the same issue when using `aria-query` with parcel. I've created an [issue at the parcel repo](https://github.com/parcel-bundler/parcel/issues/46920, but if that's not where the root cause lies, I should post it at the aria-query repo instead.

**Comment by chillaq** [comment]
Hi, which version of Parcel are you using, we are able to repro with parcel 1 version only.

**Comment by smeijer** [comment]
Yeah, it's indeed a parcel 1 issue only. Upgrading to 2 alpha helped.

**Comment by EmilianoSanchez** [comment]
@drewbolles , sorry for the delay in the notification. 

You can upgrade now the JS SDK to version 10.14.0 in your [example](https://github.com/drewbolles/parcel-split-debug) and it will work fine with Parcel 1, since we have removed `core-js` dependencies from the SDK (among other optimizations), in order to reduce its [size](https://bundlephobia.com/result?p=@splitsoftware/splitio@10.14.0).
