### ISSUE TITLE
Redis dependency required on React Native?

### ISSUE THREAD

**Issue by mking-keeper** [splitio/javascript-client#437]
After adding `@splitsoftware/splitio` to my React Native app, I noticed that `redis`-related dependencies were also pulled in.

I think these dependencies should only be necessary on the server. Is there a way I can install `@splitsoftware/splitio` without also installing `redis` libraries?

**Comment by NicoZelaya** [comment]
Hi @mking-keeper ! 

We used to have this as an optional dependency, but it was painful to some people because a failure to download `ioredis` would not make `npm install` fail.

In any case, given that React Native is client side you should be using the JS client side specific storage modules, instead of the Node ones (where we require ioredis) so it would probably not be part of your app build. 

If this is not the case we can take a look at module resolution for that build, to see what's going on. 

Assuming no issues there, will this still be something to resolve if it only downloads the dependency on the machines you run `npm install` but without actually including it on your app?

Best,
Nico.

**Comment by mking-keeper** [comment]
That makes sense, I'll check my module build to see that ioredis is excluded

**Comment by NicoZelaya** [comment]
Closing given it's old. Feel free to reopen if still experiencing this issue.
