### ISSUE TITLE
SDK performs two requests and the first one crashes with a 400 error

### ISSUE THREAD

**Issue by vihuvac** [splitio/javascript-client#499]
We are facing a strange behaviour, in our log trace we watch the SDK performs two requests, the first one crashes with a 400 error and the second one runs successfully.

- Details for the 400 error:

```bash
// Request:
{
  http {	
    method	GET
    status_code	400
    url	https://auth.split.io/api/auth
  }
  service	<our-service-name>
  span {	
    kind	client
  }
  version	0.0.53
}

// Response:
error: true
```

- Details for the success request:

```bash
{
  http {	
    method	GET
    status_code	200
    url	https://sdk.split.io/api/splitChanges
  }
  service	<our-service-name>
  span {	
    kind	client
  }
  version	0.0.53
}
```

- SDK Version: `"@splitsoftware/splitio": "^10.15.0",`

Can someone help me, please?

**Comment by NicoZelaya** [comment]
Hi @vihuvac ! The 400 is preventing you to access our streaming services but the exception should be already handled. Is this bubbling an exception up and crashing a process? 
The most probable cause is that you're running a Node process and instantiating our SDK with an API Key of type Browser instead of SDK. (https://help.split.io/hc/en-us/articles/360019916211-API-keys)

May I ask few things to help us diagnose:
- There should be another endpoint being hit by the SDK, at least after the splitChanges one returns successfully, to either `/api/segmentChanges` or `/api/mySegments`. Could you tell us which one you can see? 
- Is the application being ran in Node or in a browser?
- The authorizationKey value you're using is for which type of API Key ? . You can check in the Admin panel of your org based on the visible characters.

**Comment by vihuvac** [comment]
Hi @NicoZelaya! Thanks a lot for your response. Apologize for the delay, you were right, we were running a Node.js based process and the key had a Browser type, we created a new one as SDK and right now we ge the following error:

```
Error: socket hang up
at connResetException (internal/errors.js:610:14)
at TLSSocket.socketCloseListener (_http_client.js:400:25)
at /app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
at Scope._activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)
at Scope.activate (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
at TLSSocket.bound (/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
at TLSSocket.emit (events.js:327:22)
at TLSSocket.EventEmitter.emit (domain.js:506:15)
at net.js:674:12
at TCP.done (_tls_wrap.js:567:7)
```

These are the network details:

```
{
  error {	
    message socket hang up
  }
  http {	
    method GET
    url https://streaming.split.io/sse
  }
}
```

**Comment by chillaq** [comment]
Hi @vihuvac the error is related to the Streaming option, usually when the websocket connection error out, SDK will fall back to polling http get requests to sync the cache. So SDK functionality will not be impacted.

Could you enable debug logging for SDK and provide the log?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @vihuvac,  I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @vihuvac, I am closing out this issue. If there is still an open issue or if we can be of further assistance on this topic, feel free to re-open it.

Thanks
Bilal
