### ISSUE TITLE
Another anonoumys function causing warnings

### ISSUE THREAD

**Issue by Jakst** [splitio/javascript-client#557]
The two functions located in `src/services/request/options` are anonymous and therefore causes React warnings when transpiled (we need to transpile `@splitiosoftware/splitio-react` for IE11 support).

Could they be given names?

There was another instance of this in #535 if you want more details.

**Comment by chillaq** [comment]
Hi @Jakst , thanks for the info, checking with the team.

**Comment by EmilianoSanchez** [comment]
Hi @Jakst 

Thanks for the suggestion. With the new JS SDK release, v10.15.9, we have included proper names to those functions in order to avoid any build warnings.

I also want to mention that since React SDK v1.2.6, we are now transpiling its ESM build. This is something that was missing in previous versions, and should let you avoid transpiling `@splitiosoftware/splitio-react` for targeting IE10 or above.

Thanks
Emiliano

**Comment by Jakst** [comment]
Thanks for the heads up, then we can stop transpiling it on our end.
