### ISSUE TITLE
Feature request - option to disable syncing/polling so clients don't need to be destroyed

### ISSUE THREAD

**Issue by C-Saunders** [splitio/javascript-client#558]
The use-case I have in mind is running unit tests. We create a Split factory and client (in our case, in localhost mode when tests are being run), which prevents the tests from exiting when they're complete because it have pending timers.

We can sort of manage this with test setup and teardown functions, but it's a bit messy. I think, though I'm not sure, if we were able to do a one-time read of the local file and not poll for changes the tests would exit normally when they complete.

**Comment by chillaq** [comment]
Hi @C-Saunders, you can set the scheduler.offlineRefreshRate parameter to -1, this will cause the SDK to read the local file only once and not poll or sync afterwards.

Let me know if that works.

Thanks
Bilal

**Comment by C-Saunders** [comment]
Hi @chillaq unfortunately that didn't seem to help. It looks to me like the SDK polls with this refresh rate the same as with any other rate.

**Comment by chillaq** [comment]
Hi @C-Saunders , could you share the code used for the SDK when testing in localhost mode?

Thanks
Bilal

**Comment by C-Saunders** [comment]
@chillaq I can't share the original code, but I made a reproduction using essentially the same setup in a new repo for you to check out - https://github.com/C-Saunders/splitio-node-sdk-example

Thanks!

**Comment by chillaq** [comment]
Hi @C-Saunders, thanks for the repo, I see the issue now, the SDK does auto detect when browser window is closing or node app is shutting down and automatically call client.destroy() to stop the background synching threads, apparently when it's running in Jest, it is not detecting that automatically, which is why we have to call client.destroy before the test ends.

I will submit it as a feature request.

Thanks
Bilal
