### ISSUE TITLE
Flushing events from client at end of session is unreliable on mobile

### ISSUE THREAD

**Issue by michal-filip** [splitio/javascript-client#594]
Current implementation flushes events at the end of session as soon as "unload event" is triggered by the browser:
https://github.com/splitio/javascript-client/blob/development/src/listeners/browser.js#L40

The following docs state that this approach is very unreliable and not recommended.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#avoid_unload_and_beforeunload

I have briefly tested tracking from mobile (Chrome), interacting with a page, then ending the page session with the following results:
- when leaving the page by navigating to another url, events are flushed properly
- when closing the browser tab via browser feature, events are NOT flushed properly
- when putting the browser app in the background and then closing it via the android app manager (usual way of closing an app), events are NOT flushed properly

I have not done any further testing to confirm that the absence of "unload" event is indeed the root cause, but based on the above observations, it sounds likely to me.

This ticket is to consider taking the recommended aternate approaches mentioned on MDN page to improve the reliability of event tracking.

**Comment by chillaq** [comment]
Hi @michal-filip , thanks for the info, I will check with the team.
You can always call client.destroy() when you don't need the SDK anymore, this will flush the cached events.

**Comment by chillaq** [comment]
Hi @michal-filip, I submitted a feature request on your behalf, as this is a change in SDK design rather than a bug.

Checkout the CHANGES.txt when new versions are published to see if this feature is implemented.

Thanks
Bilal

**Comment by EmilianoSanchez** [comment]
Hi @michal-filip, 
I wanted to let you know that we have finally addressed your request in version 10.21.0 of @splitsoftware/splitio (check changelog [here](https://github.com/splitio/javascript-client/blob/development/CHANGES.txt#L3)).

By following the recommendation stated here https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#avoid_unload_and_beforeunload, 
the SDK now relies on `visibilitychange` and `pagehide` events, instead of `unload`, to extend the coverage of mobile and desktop browsers.

Thanks,
Emiliano
