### ISSUE TITLE
Vulnerability in package dependency "eventsource"

### ISSUE THREAD

**Issue by DaleGardner** [splitio/javascript-client#665]
After installing the latest version of this package (v10.18.1) and running a security scan, there is an issue identified:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0691

It comes from the "eventsource" dependency of this package, this is the chain:
@splitsoftware/splitio > eventsource > original > url-parse

I'm not able to pass in my pipeline as this is a required gate. If this could be updated or a replacement found, it would be very helpful so that this package can pass security scans.

**Comment by chillaq** [comment]
Hi @DaleGardner , thanks for the info, checking with the team.

**Comment by gsiwatch** [comment]
For now I think if we are using the yarn package then we can add the following as resolution to fix it temporarily at the client side:

    "resolutions": {
        "url-parse": "1.5.10",
        "eventsource": "2.0.2"
    },

**Comment by chillaq** [comment]
Thanks @gsiwatch, you can actually upgrade url-parse to "1.5.0", this will fix the issue.
You can also run "npm audit fix" or "npm_config_yes=true npx yarn-audit-fix"

**Comment by DaleGardner** [comment]
@chillaq  This issue still remains though, it isn't fixed. Every consumer of this package would have to workaround this issue, instead of addressing the vulnerability here. This repo is the source of this dependency.

How is there any justification to close this issue as "completed"?

**Comment by chillaq** [comment]
Hi @DaleGardner, That is correct, we opted not to apply the fix on our side as the solution will impact   streaming feature on some old versions of NodeJS. We will create a knowledge base article to document the workaround.

**Comment by DaleGardner** [comment]
@chillaq  I see

> We will not update EventSource dependency to v2 for now, because it implies dropping streaming support for NodeJS below v12.
 - @EmilianoSanchez 

Below v12? Even v12 is no longer supported: https://nodejs.org/en/about/releases/

Also, I see besides this issue there is one previously closed for the same, and now there is a new issue opened also on this same problem.

The fact of the matter is that for the majority of your base, who are adhering to best practices (using actively supported software), this package is effectively broken and requires workaround with the latest version.

Probably you should drop support for the unsupported node versions. But if not, the least action should be to fix this in the mainstream stable version (issue a new major version if needed) so it is default secure and working. Then issue a separate version branch for deprecated support for consumers of old node versions.

That's how pretty much all other libraries handle this situation, like node itself. They would have the v12 and keep releasing new versions on that tag, while simultaneously updating v14, and so forth.

**Comment by DaleGardner** [comment]
Tagging related: 
#675 
#678 
#656 
#677

**Comment by EmilianoSanchez** [comment]
Hi @DaleGardner, 

We are going to update it soon. I just need to confirm with the team, because the update implies a breaking change, due to dropping support for Nodejs below [version 12](https://github.com/EventSource/eventsource/blob/master/HISTORY.md#200), which anyway, as you mentioned, are unmaintained now.

**Comment by aliwatters** [comment]
We have multiple teams/services impacted by this -- any eta?

Bumping major `"version": "11.0.0",` when you drop support for node v12 would be reasonable.

**Comment by EmilianoSanchez** [comment]
Hi @aliwatters . I am sorry for the delay, but we will release the fix next week.

**Comment by NicoZelaya** [comment]
Hi @DaleGardner and @aliwatters !

My name is Nicolas Zelaya and I work with the SDK team here at Split. May I ask one of you to try installing the SDKs currently latest version, 10.19.0 by running `npm update @splitsoftware/splitio` and re-validate the vulnerability?

Our SDK was already compatible with eventsource 1.11.1 but this version also has the package-lock.json updated so you should get that specific version, as well as url-parse 10.15.10 which has the vulnerability already patched.
Eventsource 1.11.1 also fixes the vulnerability on [issue #677](https://github.com/splitio/javascript-client/issues/677).

Please do let us know if you still get it reported due to our SDK though, so we can pursue other alternatives.

Thanks in advance!
Nicolas.

**Comment by t0mdev** [comment]
That did it. After regenerating the package-lock.json eventsource 1.11.1 is used, which fixes the vulnerability. Thanks!

**Comment by NicoZelaya** [comment]
Thank you @t0mdev for sharing confirmation!

I'll close out this issue but if any person following it still sees the vulnerability after updating the SDK or these libraries themselves, feel free to reopen or write to support@split.io referencing this issue and asking to talk with Nicolas Zelaya, and we'll help you get it resolved. 

Best regards,
Nicolas Zelaya.

**Comment by DaleGardner** [comment]
Still the same issue for me
![image](https://user-images.githubusercontent.com/3970939/171950214-1ba8076d-7b3e-4e3b-ba8d-dc487d8ce091.png)

**Comment by DaleGardner** [comment]
@NicoZelaya 
You would need to set your minimum version to 1.11.1 to ensure that, I still see that 1.0.7 is set:
https://github.com/splitio/javascript-client/blob/development/package.json#L43-L44

**Comment by DaleGardner** [comment]
After deleting package-lock and reinstalling latest of everything, 1.10.0 is the closest I could get, which still fails:
![image](https://user-images.githubusercontent.com/3970939/171958829-3dc0d018-16ba-4336-b999-e6c65b854097.png)

Please fix

**Comment by DaleGardner** [comment]
@NicoZelaya  I am unable to reopen this issue. It should be reopened as issue still remains despite now slipping past the promised timeline for a fix.

Any consumer of this package is not guaranteed to get a secure version even when getting the latest version (10.19.0). Extremely likely that they would pull a vulnerable version of eventsource (since the Split package is not specifying a fixed version explicitly), especially given that it will not pull anything newer with any existing package-lock (which is to say, any existing project).

**Comment by NicoZelaya** [comment]
Hey @DaleGardner. I'll reopen it momentarily. 

Can you help me validate your same scenario by providing the outcome of `npm ls eventsource` and `npm ls url-parse` ? Or if you feel comfortable sharing the full list with for example `npm ls --depth=15` 

I would assume there is a different package asking for a version of these libraries that might not be satisfied with eventsource 1.1.1. I want to make sure that changing our minimum version which we can do today won't conflict with this and the resolution will be what we expect.
The assumption was that if Split was the only package that introduced this vulnerability that was already fixed as well, apologies for that.

**Comment by DaleGardner** [comment]
@NicoZelaya 
![image](https://user-images.githubusercontent.com/3970939/172211033-ca5ba12e-bae0-492c-8fd0-f5cbc7fe52eb.png)

![image](https://user-images.githubusercontent.com/3970939/172211086-7e445ce6-2219-4686-b706-07411bd8b040.png)

Changing your minimum version would not break anything. Npm would simply pull another version to satisfy. It just dedupes if one version can satisfy multiple dependencies, but it will pull whatever it needs to for each package.

**Comment by DaleGardner** [comment]
@NicoZelaya I updated with the latest RC published, which takes eventsource@1.1.1, but that does not fix the problem. See security scan output of latest splitio@10.19.1-rc0:

![image](https://user-images.githubusercontent.com/3970939/172444675-a902b00b-8d4c-459c-926c-d48ec1bde2e1.png)

**Comment by DaleGardner** [comment]
@NicoZelaya I don't have time to attempt further workarounds. I've already spent far too much time and this issue was from April, I really can't justify it anymore. If you updated your dependencies to secure versions there would not be any problem and you'd be adherent to the security advisories. I do not understand the lack of urgency or respect for security issues.

**Comment by NicoZelaya** [comment]
@DaleGardner  I apologize for the perception you have here, but we've already patched eventsource which is what we use and you still see the vulnerable version of url-parse. 
For some reason that I can't validate with just our SDK and the angular dependency you shared, the resolution of url-parse is still yielding version `1.4.7` in your screenshot instead of `1.5.10`. 
I'm not asking for you to attempt any workarounds, but rather, to give us the dependency data of your app so we can figure that one out for you, as other people has confirmed this version fixed it for them. 
I need your dependency tree to understand where it comes from since our package-lock has different version.

While we could add the explicit dependency to url-parse in an attempt to fix it for you, it would be suboptimal, since it's a dependency of a dependency of a dependency for us. I understand that `original 1.0.2` allows for the vulnerable url-parse versions, but our package-lock has v1.5.10.
And it is very likely that if some other dependency you have is not satisfied with this version, you'll still have the vulnerability regardless of what we do, which is basically what I would like to figure out how to resolve instead of just working on removing Split from the picture. 

We are trying to help here and it is definitely not our intent to ask you to try workarounds, but rather, to be able to replicate what you see and provide a solution.

**Comment by DaleGardner** [comment]
@NicoZelaya From the security scan I posted above it is identifying six security issues and they are all stemming from splitio package. There are no other problems reported in the scan (which is scanning the entire project). These are indeed workarounds to a proper solution of not including vulnerable dependency versions. You've already said as much by admitting that it allows for vulnerable versions. It is a crapshoot at best.

If the security scan is wrong in identifying issues pertaining to splitio package, I would suggest taking that up with Snyk.io support and open a ticket with them.
https://github.com/snyk

**Comment by NicoZelaya** [comment]
@DaleGardner I very much apologize for all the inconveniences this has been causing to you, the pain and the time invested. All I'm trying to do is help here with the information I have available. 

The reason why I ask for the package-lock.json file is to confirm from where that dependency is coming from and why it is resolving to this particular version of url-parse even after you've installed the rc. 
From my end both the Dependabot from Github and Snyk where I've just scanned an updated fork as you can see below alert about any vulnerabilities. I can try scanning the main repository of course if you think that might show me what you see.

<img width="1437" alt="Screen Shot 2022-06-07 at 10 42 52 PM" src="https://user-images.githubusercontent.com/5522668/172514037-fad0a681-9028-41d9-a7b7-47f616f08ef7.png">

I also want to clarify that I did not think we're particularly allowing for a vulnerable dependency, but that we use eventsource@1.1.1 which uses original@1.0.2 which in turn, has a version range for url-parse that does not restrict all the versions with problems. 

I would still very much like to be able to reproduce your scenario or get in touch via Zendesk to schedule a Zoom call (doesn't have to be long) to work it out and put this struggles you're facing behind. I understand what you're seeing and I'm trying to get a full explanation I can work out and most importantly, validate a solution from my end to avoid asking you unnecessary tests.

Thanks in advance,
Nicolas Zelaya.

**Comment by NicoZelaya** [comment]
@DaleGardner the only thing we haven't tried is to define a dependency for `url-parse@1.5.10` but since it's a dep of a dep of a dep, it wouldn't be entirely correct. If either eventsource stops depending on original, or original drops url-parse we would need to remove it to avoid an unnecessary one.
I do not think this is a very good solution thinking on everyone and how npm should be used, are you suggesting a different option to "fix" it? 

But as I've shared in the screenshot, Snyk (which I understand is what you're using) is not marking our package as vulnerable. Neither is Dependabot, so what I want to understand is why you are getting it, since it's not something everybody is facing. And we don't have an app where we can repro your scenario.

Assuming your goal is to resolve this, can you help us understand why you are still there getting it? by sharing the requested package.json and package-lock.json ? Or have a zoom session with us? 
And also, can you confirm you've regenerated package-lock or at the very least, updated these dependencies on the package-lock running `npm update`? 
Which commands did you run so far? The `npm install @splitsoftware/splitio` will respect your package-lock, so you'll need to run an npm update or similar at some point.

Seeing those files and knowing which commands have you ran, will tell us why you're still having the vulnerability and how it can be resolved. Please share this information with us, or your proposed solution so we can work towards resolution.

Thanks in advance!

**Comment by DaleGardner** [comment]
@NicoZelaya Well EventSource already dropped it in v2.0.2 and the proposed solution was posted earlier in this thread. Update EventSource to latest and issue a new major ver v11, noting the drop of support for Node <= v11.

I'm more concerned about others that may not be checking this thread and aren't regenerating their package-lock, etc. If that makes sense.

**Comment by DaleGardner** [comment]
@NicoZelaya The issue was already perfectly fixed two weeks ago in this PR: #679 
Including new version and updating Node support and everything, but you closed it.

**Comment by NicoZelaya** [comment]
@DaleGardner The eventsource package was patched the exact same day for 2.0.2 and 1.1.1 with the vulnerability fix they had. We are open to push a breaking change if it's proven to be necessary (for many reasons that I could have shared over Zoom we'll drop Node <12, not just 11). 

I've asked a couple times for your package.json and package-lock.json files and to understand which commands you've run already, because of the reasons shared in previous messages: We want to be able to repro your scenario and validate a fix for you, regardless of it being a breaking change or not.

There's multiple reasons why a breaking change now is not convenient just for this, which I can share over a different channel, but I do not know why you prefer to communicate 100% here instead of through other channels (ZD or Zoom). If you're interested, those channels are of course still open.

Now all I know so far is your lockfile is in your domain and we shouldn't need to enforce an update of dependencies of a lower level in you behalf. And the effort, AFAIK, of running `npm install @splitsoftware/splitio@11.0.0` or `npm update url-parse` is the same (which I do not know if you've executed). 
The update command would only require you push a new version of your lockfile, the new Split version installation requires pushing new versions of both files. 

To summarize where I think we are now:
-  You still see vulnerabilities from url-parse, highlighted by Snyk. This is of course not great.
- Snyk does not detect any vulnerabilities in our package, so this one I assume is in the lockfile of your project. This is, I think (can't confirm without your lockfile) fixable for good with just one command.
- We have 0 visibility into why, even with multiple scans, we don't see the vulnerability but your project is.
- We have 0 visibility into which commands you've run so far, or what has been done on your end.
- We do not see any vulnerabilities in our scans from dependabot or other sources either.
- We are not saying we will never drop Node <12, we are just saying, not as a patch for this vulnerability. We will make a breaking change that has this upgrade amongst other ones like the version for ioredis. 

What I propose:
- In the communication channel of your choice, please share the requested information (package.json, package-lock.json, and what commands have you used that led to that state if any) so we can provide proper support for you to get the vulnerability resolved. In a way we can validate the solution. We are definitely open for the breaking change if we can prove the need for it.
- I also offer a Zoom meeting to share any extra context into why we do not want to push a breaking change just for this situation unless it's needed. Whenever we do it, we'll maintain the previous major for a year nevertheless. 

I definitely understand this: 
> I'm more concerned about others that may not be checking this thread and aren't regenerating their package-lock, etc. If that makes sense.

Your shared files will help us understand this case and the best upgrade path and if we need to add any visible callouts to our docs or the readme of this repo.

Let's work together to solve this if you're open! And if my ask is for data you can't share, let's figure out how we can repro your scenario to validate a solution or work it out in a Zoom (then we can add any outcomes on this thread).

Many thanks in advance, 
Nico

**Comment by NicoZelaya** [comment]
@DaleGardner I've just published the version `@splitsoftware/splitio@10.19.1-rc1` with this update, can you give it a try and confirm the vulnerability is not there anymore? In the meantime we'll validate it, probably releasing the stable version either today or early

**Comment by NicoZelaya** [comment]
Hey @DaleGardner, version 10.19.1 (stable) is out in case you prefer to use this version, I'll be closing this issue and hopefully we won't need to reopen it! But let us know if you experience any further issues.

Have a wonderful week,
Nico.
