### ISSUE TITLE
Explicitly say js sdk requires tslib or importHelpers: true

### ISSUE THREAD

**Issue by n0th1ng-else** [splitio/javascript-client#753]
Hello. We have a NextJS application and now we are integrating with split.io. 
In fact, we faced some unexpected behavior **in the runtime**:

```
Cannot find module 'tslib'
Require stack:
- /app/node_modules/@splitsoftware/splitio/lib/sync/offline/splitsParserFromFile.js
- /app/node_modules/@splitsoftware/splitio/lib/sync/offline/LocalhostFromFile.js
- /app/node_modules/@splitsoftware/splitio/lib/settings/node.js
- /app/node_modules/@splitsoftware/splitio/lib/factory/node.js
- /app/node_modules/@splitsoftware/splitio/lib/index.js
```

Looking into the source code of split JS sdk I did not find any mentions of `tslib` and we do not use it in the application as well. In fact, I see the split SDK is. compiled using the [importHelpers: true](https://github.com/splitio/javascript-client/blob/development/tsconfig.json#L21) Typescript flag, which actually emits tslib wrappers. 

Can we add a peerDependencies for the package? and it would be nice to have this behavior documented in the installation guides

**Comment by EmilianoSanchez** [comment]
Hi @n0th1ng-else , 

It is uncommon to have that issue because the `tslib` module is a dependency of the `@splitsoftware/splitio-commons` package, which is in turn a dependency of `@splitsoftware/splitio`. So, `tslib` should be installed automatically when you install `@splitsoftware/splitio`. That's why we set `importHelpers: true` to import helper functions from `tslib` and avoid duplicating the code of those functions across the SDK transpiled code.

Probably there was some installation issue on your side, or some nested dependency problem with `tslib`. So I would recommend either to install it manually (`npm install tslib --save`), as if it were a peer-dependency as you mentioned, or reinstall your packages, by deleting `node_modules` directory and `package-lock.json` file, and running `npm install` again.

**Comment by n0th1ng-else** [comment]
Thank you Emiliano

That a good call, the tslib is indeed in splitio-commons in dependencies section 👍🏿

Now I have more information that I am trying to deep dive into:

with `npm ci` it works just fine, but in the docker we run `npm ci --omit=dev`, thus facing the problem. I am trying to understand why tslib is not emitted in the root of node_modules although all dependencies are regular dependencies, not devDependencies
