### ISSUE TITLE
Filtering whitelist ids to prevent exposing email addresses to all tenants

### ISSUE THREAD

**Issue by audiolion** [splitio/javascript-client#790]
Hey 👋 

We recently discovered that when split loads feature flag changes, it will pull every email address in the whitelist for each treatment. This means that customers can potentially see email addresses for other customers by looking at the network traffic. Is there a way to assign a filter in split so that only whitelist emails from a specific domain or set of domains are pulled?

**Comment by agustinona** [comment]
Hi @audiolion it is not possible to selectively filter out parts of your feature flag definitions. If you want to target email addresses in your feature flags but don't want them exposed as part of your FF definitions you may use segments for targeting instead (see our [docs](https://help.split.io/hc/en-us/articles/360020407512-Create-a-segment) on segments). Client side SDKs do not pull segment contents, but rather segment memberships for the key (in this case the email address) in use so other email addresses would not be exposed.

That being said, we do recommend you you avoid using PII such as email addresses as your main keys for this same reason, so you may consider using something like userIds, or hashed email addresses instead.

**Comment by audiolion** [comment]
Hi @agustinona thanks for the response. Those solutions make sense as workarounds, but I would consider them workarounds. The pain point of using an internal user id or hashing an email address is that it makes it harder for non-engineering groups like customer success, product, et al. to use the split web app. They now need to know how to hash emails or lookup user ids and match them to emails. Using segments works but it is more of a band-aid, particularly if you are trying to whitelist only an email or two, you will end up making a segment for every email address, which is worse than obfuscating the user key.

In general I think the whitelist filtering out emails, or offering a solution like a [relay-proxy](https://github.com/launchdarkly/ld-relay?tab=readme-ov-file#launchdarkly-relay-proxy) where we could filter the values returned would be ideal.

**Comment by agustinona** [comment]
@audiolion I understand. In order to bridge the gap for non-engineering folks you can make use of our [attributes API](https://docs.split.io/reference/attributes-overview) to create identities. Using this API you can associate each hashed ID to their corresponding email. Then in the targeting editor (or anywhere in the web console) when targeting an ID people can just enter the desired email and it will work as a search function showing any IDs that match it.

I read the documentation for the relay-proxy but I'm not sure what filtering capabilities you are referring to. If you could point me in the right direction I'm happy to help you find an equivalent setup using our available tools, or submit an RFE on your behalf if applicable. One thing to keep in mind is that our SDKs work using client side evaluation. This enables Split to serve treatments without requiring you to share any potentially sensitive information about your users outside your application. On the flipside this means our SDKs need to fetch complete definitions instead of just treatments or user-specific clauses. When including user identifiers in the definitions themselves may be a concern, using segments is the way of having client-side SDKs fetch only user-specific data for targeting purposes.

**Comment by agustinona** [comment]
I'm marking this as closed and have submitted the relevant RFEs for our team to evaluate. Feel free to reopen if you have any concerns.

**Comment by audiolion** [comment]
Sorry meant to reply back, didn't know about the attributes api before, looks like it should solve this problem, thanks!
