### ISSUE TITLE
SplitFilter using byPrefix 

### ISSUE THREAD

**Issue by gsiwatch** [splitio/javascript-client#791]
@EmilianoSanchez 
I am seeing [byPrefix](https://github.com/splitio/javascript-client/blob/4d6406d4d8b520961701e87047f51ac36de28d51/types/splitio.d.ts#L917) as the allowed SplitFilterType type but when I tried to search documentation around 'byPrefix' at the official website, [no result came up](https://help.split.io/hc/en-us/search?utf8=%E2%9C%93&query=byPrefix). Is byPrefix still allowed as SplitFilterType property in the latest version of split sdk.

**Comment by EmilianoSanchez** [comment]
Hi @gsiwatch ,

Sorry for the inconvenience. 
Yes, `byPrefix` is still allowed, but with version 10.24.0, we decided to move forward in favor of filtering by flag sets (`bySet` as SplitFilter type), which is supported across all our SDKs. More details can be found in our [Docs](https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#multiple-evaluations-at-once) and [Blog post](https://www.split.io/blog/minimize-webpage-latency-with-split-flag-sets/).

The main idea is to deprecate and remove `byPrefix` in the next major release, which is why it is not documented. We recommend using `bySet` or `byName` filter types instead.

In addition, if you have a specific use case for using `byPrefix` rather than the other options, could you please share it? 

Thank you in advance.

**Comment by agustinona** [comment]
@gsiwatch I'm closing this issue now. If you have any further concerns or have any additional feedback please feel free to reopen.
